{
 "title": "Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": "label_values(up, hostname)" },
   {
    "name": "nic",
    "query": "label_values(node_network_device_id, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU ($hostname)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (groupname, hostname) (rate(namedprocess_namegroup_cpu_seconds_total{hostname=~\"$hostname\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{hostname=~\"$hostname\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory ($hostname)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (groupname, hostname) (rate(namedprocess_namegroup_memory_bytes{hostname=~\"$hostname\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network ($hostname)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{hostname=~\"$hostname\",device=~\"$nic\"}[$__interval])",
     "legendFormat": "rx ({{device}})"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total{hostname=~\"$hostname\",device=~\"$nic\"}[$__interval])",
     "legendFormat": "tx ({{device}})"
    }
   ]
  },
  {
   "title": "Disk Usage ($hostname)",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 51 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{hostname=~\"$hostname\"} / node_filesystem_size_bytes{hostname=~\"$hostname\"})",
     "legendFormat": "{{device}} ({{mountpoint}})"
    }
   ]
  },
  {
   "title": "File Descriptors ($hostname)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{hostname=~\"$hostname\"}/node_filefd_maximum{hostname=~\"$hostname\"}",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}